"""drop occupancy not exceed capacity constraint

Revision ID: 324f243bcd06
Revises: 95b383fbb78a
Create Date: 2026-08-16 01:56:48.379472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324f243bcd06'
down_revision: Union[str, Sequence[str], None] = '95b383fbb78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_shelter_occupancy_not_exceed_capacity'), 'shelters', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_shelter_occupancy_not_exceed_capacity'), 'shelters', 'capacity IS NULL OR current_occupancy IS NULL OR current_occupancy <= capacity')
    # ### end Alembic commands ###
