"""make shelter capacity and current_occupancy nullable

Revision ID: 95b383fbb78a
Revises: 2027c3b47ffb
Create Date: 2026-08-16 01:27:57.917885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95b383fbb78a"
down_revision: Union[str, Sequence[str], None] = "2027c3b47ffb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("shelters", "capacity", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "shelters", "current_occupancy", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint("ck_shelter_capacity_positive", "shelters", type_="check")
    op.drop_constraint("ck_shelter_occupancy_non_negative", "shelters", type_="check")
    op.drop_constraint(
        "ck_shelter_occupancy_not_exceed_capacity", "shelters", type_="check"
    )
    op.create_check_constraint(
        "ck_shelter_capacity_positive", "shelters", "capacity IS NULL OR capacity > 0"
    )
    op.create_check_constraint(
        "ck_shelter_occupancy_non_negative",
        "shelters",
        "current_occupancy IS NULL OR current_occupancy >= 0",
    )
    op.create_check_constraint(
        "ck_shelter_occupancy_not_exceed_capacity",
        "shelters",
        "capacity IS NULL OR current_occupancy IS NULL OR current_occupancy <= capacity",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shelters", "current_occupancy", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("shelters", "capacity", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint("ck_shelter_capacity_positive", "shelters", type_="check")
    op.drop_constraint("ck_shelter_occupancy_non_negative", "shelters", type_="check")
    op.drop_constraint(
        "ck_shelter_occupancy_not_exceed_capacity", "shelters", type_="check"
    )
    op.create_check_constraint(
        "ck_shelter_capacity_positive", "shelters", "capacity > 0"
    )
    op.create_check_constraint(
        "ck_shelter_occupancy_non_negative", "shelters", "current_occupancy >= 0"
    )
    op.create_check_constraint(
        "ck_shelter_occupancy_not_exceed_capacity",
        "shelters",
        "current_occupancy <= capacity",
    )
    # ### end Alembic commands ###
