"""create shelters table

Revision ID: b5d45e5dcd2b
Revises: 
Create Date: 2026-08-14 16:22:12.102704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d45e5dcd2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('neighborhood', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_occupancy', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FULL', 'CLOSED', name='shelterstatus'), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_shelter_capacity_positive'),
    sa.CheckConstraint('current_occupancy <= capacity', name='ck_shelter_occupancy_not_exceed_capacity'),
    sa.CheckConstraint('current_occupancy >= 0', name='ck_shelter_occupancy_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelters_city'), 'shelters', ['city'], unique=False)
    op.create_index(op.f('ix_shelters_department'), 'shelters', ['department'], unique=False)
    op.create_index(op.f('ix_shelters_status'), 'shelters', ['status'], unique=False)
    op.create_index(op.f('ix_shelters_verification_status'), 'shelters', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shelters_verification_status'), table_name='shelters')
    op.drop_index(op.f('ix_shelters_status'), table_name='shelters')
    op.drop_index(op.f('ix_shelters_department'), table_name='shelters')
    op.drop_index(op.f('ix_shelters_city'), table_name='shelters')
    op.drop_table('shelters')
    # ### end Alembic commands ###
